// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dyQBcscJPo7ysxi3T9SyPcSbdu9Dl0Q',
    appId: '1:128900994227:web:6521a0f18c9c03cb1d4cc6',
    messagingSenderId: '128900994227',
    projectId: 'movieapp-4f5a5',
    authDomain: 'movieapp-4f5a5.firebaseapp.com',
    storageBucket: 'movieapp-4f5a5.firebasestorage.app',
    measurementId: 'G-2W0E39PXXK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Y9r1gV_M4-SsO6fAwDNaptbEHP9TK6k',
    appId: '1:128900994227:ios:3e7a15d08d2fbe881d4cc6',
    messagingSenderId: '128900994227',
    projectId: 'movieapp-4f5a5',
    storageBucket: 'movieapp-4f5a5.firebasestorage.app',
    iosBundleId: 'com.example.itiTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2dyQBcscJPo7ysxi3T9SyPcSbdu9Dl0Q',
    appId: '1:128900994227:web:6522d0cf6992b5721d4cc6',
    messagingSenderId: '128900994227',
    projectId: 'movieapp-4f5a5',
    authDomain: 'movieapp-4f5a5.firebaseapp.com',
    storageBucket: 'movieapp-4f5a5.firebasestorage.app',
    measurementId: 'G-VG77YJNB36',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Y9r1gV_M4-SsO6fAwDNaptbEHP9TK6k',
    appId: '1:128900994227:ios:3e7a15d08d2fbe881d4cc6',
    messagingSenderId: '128900994227',
    projectId: 'movieapp-4f5a5',
    storageBucket: 'movieapp-4f5a5.firebasestorage.app',
    iosBundleId: 'com.example.itiTraining',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIxPhqlzDfD-kN8EU_m6LDnNkxwQ-qtL4',
    appId: '1:128900994227:android:64f389aa81f4ac481d4cc6',
    messagingSenderId: '128900994227',
    projectId: 'movieapp-4f5a5',
    storageBucket: 'movieapp-4f5a5.firebasestorage.app',
  );
}
